#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PhotoGridView.Resource", IsApplication=true)]

namespace PhotoGridView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FlowerBuds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Fruits = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Legumes = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Tubers = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Vegetables = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int ArrayButton = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int CursorButton = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int Heading = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int Image = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int List = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int button1 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int button2 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int button3 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int button4 = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int gallery1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int gridView1 = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EmptyLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
